// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DpiUIClient is the client API for DpiUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DpiUIClient interface {
	// ListEngineSpecs returns a list of Deep Packet Inspection Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (DpiUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type dpiUIClient struct {
	cc grpc.ClientConnInterface
}

func NewDpiUIClient(cc grpc.ClientConnInterface) DpiUIClient {
	return &dpiUIClient{cc}
}

func (c *dpiUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (DpiUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DpiUI_ServiceDesc.Streams[0], "/v1.DpiUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &dpiUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DpiUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type dpiUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *dpiUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dpiUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.DpiUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DpiUIServer is the server API for DpiUI service.
// All implementations must embed UnimplementedDpiUIServer
// for forward compatibility
type DpiUIServer interface {
	// ListEngineSpecs returns a list of Deep Packet Inspection Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, DpiUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedDpiUIServer()
}

// UnimplementedDpiUIServer must be embedded to have forward compatible implementations.
type UnimplementedDpiUIServer struct {
}

func (UnimplementedDpiUIServer) ListEngineSpecs(*ListEngineSpecsRequest, DpiUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedDpiUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedDpiUIServer) mustEmbedUnimplementedDpiUIServer() {}

// UnsafeDpiUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DpiUIServer will
// result in compilation errors.
type UnsafeDpiUIServer interface {
	mustEmbedUnimplementedDpiUIServer()
}

func RegisterDpiUIServer(s grpc.ServiceRegistrar, srv DpiUIServer) {
	s.RegisterService(&DpiUI_ServiceDesc, srv)
}

func _DpiUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DpiUIServer).ListEngineSpecs(m, &dpiUIListEngineSpecsServer{stream})
}

type DpiUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type dpiUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *dpiUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DpiUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DpiUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DpiUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DpiUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DpiUI_ServiceDesc is the grpc.ServiceDesc for DpiUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DpiUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DpiUI",
	HandlerType: (*DpiUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _DpiUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _DpiUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dpi-ui.proto",
}
